CREATE DATABASE Enunciado2;
USE Enunciado2;

CREATE TABLE IF NOT EXISTS Aerolinea(
ID_Aerolinea INT NOT NULL AUTO_INCREMENT,
Nombre_Aerolinea VARCHAR(40) NOT NULL
PRIMARY KEY(ID_Aerolinea) 
)ENGINE=InnoDB;'sólo existe soporte para claves foráneas en tablas de tipo InnoDB.'


CREATE TABLE IF NOT EXISTS Viaje(
ID_Viaje INT NOT NULL AUTO_INCREMNT,
Numero_Vuelo INT NOT NULL,
Numero_Pasajeros INT NOT NULL,
Fecha_Hora_Despegue DATETIME NOT NULL,
Fecha_Hora_Aterrizaje DATETIME NOT NULL,
Vuelo_Directo VARCHAR(10) NOT NULL,
PRIMARY KEY(ID_Viaje),
FOREIGN KEY(ID_Aerolinea) REFERENCES Aerolinea(ID_Aerolinea)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Avion(
ID_Avion INT NOT NULL AUTO_INCREMENT,
Modelo INT NOT NULL,
Matricula INT NOT NULL,
Galon_Gasolina_Maximo INT NOT NULL,
Distancia_Maxima_Viaje INT NOT NULL,
Altura_Maxima_Soportada INT NOT NULL,
PRIMARY KEY(ID_Avion),
FOREIGN KEY(ID_Viaje) REFERENCES Viaje(ID_Viaje)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Clase_Vuelo(
ID_Clase INT NOT NULL AUTO_INCREMENT,
Nombre_Clase VARCHAR(40) INT NOT NULL,
Numero_Asiento INT NOT NULL,
PRIMARY KEY(ID_Clase),
FOREIGN KEY(ID_Avion) REFERENCES Avion(ID_Avion)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Mantenimiento(
ID_Mantenimiento INT NOT NULL AUTO_INCREMENT,
Nombre_Mantenimiento VARCHAR(40) NOT NULL,
Programado VARCHAR(10) NOT NULL,'TRUE OR FALSE'
Fecha_Hora_Mantenimiento DATETIME NOT NULL,
Fecha_Hora_ProxMantenimiento DATETIME NOT NULL,
Detalle_Mantenimiento VARCHAR(50) NOT NULL,
PRIMARY KEY(ID_Mantenimiento),
FOREIGN KEY(ID_Avion) REFERENCES Avion(ID_Avion)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Cliente(
ID_Cliente INT NOT NULL AUTO_INCREMENT,
CUI INT NOT NULL,
Nombre_Cliente VARCHAR(40) NOT NULL,
Apellido_Cliente VARCHAR(40) NOT NULL,
Edad INT NOT NULL,
Fecha_Nacimiento DATE NOT NULL,
Correo VARCHAR(40) NOT NULL,
Telefono INT NOT NULL,
Direccion VARCHAR(40) NOT NULL,
Numero_Pasaporte INT NOT NULL,
PRIMARY KEY(ID_Cliente),
FOREIGN KEY(ID_Viaje) REFERENCES Viaje(ID_Viaje)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Ciudad(
ID_Ciudad INT NOT NULL AUTO_INCREMENT,
Nombre_Ciudad VARCHAR(40) NOT NULL,
PRIMARY KEY(ID_Ciudad)
)ENGINE=InnoDB;



CREATE TABLE IF NOT EXISTS Codigo_Postal(
ID_Codigo_Postal INT NOT NULL AUTO_INCREMENT,
Numero_Codigo_Postal INT NOT NULL,
PRIMARY KEY(ID_Codigo_Postal),
FOREIGN KEY(ID_Ciudad) REFERENCES Ciudad(ID_Ciudad)
ON DELETE NO ACTION
)ENGINE=InnoDB;



CREATE TABLE IF NOT EXISTS Formulario_Boleto(
ID_Formulario INT NOT NULL AUTO_INCREMENT,
Fecha_Formulario DATE INT NOT NULL,
Fecha_Viaje DATE INT NOT NULL,
PRIMARY KEY(ID_Formulario),
FOREIGN KEY(ID_Cliente) REFERENCES Cliente(ID_Cliente),
FOREIGN KEY(ID_Codigo_Postal) REFERENCES Codigo_Postal(ID_Codigo_Postal)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Boleto(
ID_Boleto INT NOT NULL AUTO_INCREMENT,
Numero_Boleto INT NOT NULL,
Peso_Equipaje INT NOT NULL,
Fecha_Reembolso DATE INT NOT NULL,
Fecha_Cambios DATE INT NOT NULL,
PRIMARY KEY(ID_Boleto),
FOREIGN KEY(ID_Cliente) REFERENCES Cliente(ID_Cliente)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Pago(
ID_Pago INT NOT NULL AUTO_INCREMENT,
Forma_de_Pago VARCHAR(40) NOT NULL,
Numero_de_Pago INT NOT NULL,
Monto_Total INT NOT NULL,
Fecha_Pago DATE NOT NULL,
PRIMARY KEY(ID_Pago),
FOREIGN KEY(ID_Formulario_Boleto) REFERENCES Formulario_Boleto(ID_Formulario_Boleto)
ON DELETE NO ACTION

)ENGINE=InnoDB;




CREATE TABLE IF NOT EXISTS Empleado(
ID_Empleado INT NOT NULL AUTO_INCREMENT,
CUI INT NOT NULL,
Nombre_Empleado VARCHAR(40) NOT NULL,
Apellido_Empleado VARCHAR(40) NOT NULL,
Edad INT NOT NULL,
Direccion VARCHAR(40) NOT NULL,
Fecha_Contratacion DATE NOT NULL,
Fecha_Nacimiento DATE NOT NULL,
Correo VARCHAR(40) NOT NULL,
Telefono INT NOT NULL,
Empleado_Activo VARCHAR(10) NOT NULL,'TRUE | FALSE',
PRIMARY KEY(ID_Empleado),
FOREIGN KEY(ID_Aerolinea) REFERENCES Aerolinea(ID_Aerolinea)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Ex_Empleado(
ID_Ex_Empleado INT NOT NULL AUTO_INCREMENT,
Despido_Retiro VARCHAR(10) NOT NULL,
Fecha_Dejo_Puesto DATE NOT NULL,
Razon_Dejo_Puesto VARCHAR(40) NOT NULL,
PRIMARY KEY(ID_Ex_Empleado),
FOREIGN KEY(ID_Empleado) REFERENCES Empleado(ID_Empleado)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Tipo_Empleado(
ID_Tipo_Empleado INT NOT NULL AUTO_INCREMENT,
Nombre_Tipo VARCHAR(40) NOT NULL,
Sueldo INT NOT NULL,
Jornada_Laboral VARCHAR(40) NOT NULL,
Pertenece_Tripulacion VARCHAR(10) NOT NULL,
RIMARY KEY(ID_Tipo_Empleado),
FOREIGN KEY(ID_Empleado) REFERENCES Empleado(ID_Empleado)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Asistencia(
ID_Asistencia INT NOT NULL AUTO_INCREMENT,
Hora_Inicio_Labor TIME NOT NULL,
Hora_Fin_Labor TIME NOT NULL,
Detalle VARCHAR(40) NOT NULL,
Ausente VARCHAR(10) NOT NULL,
PRIMARY KEY(ID_Tipo_Empleado),
FOREIGN KEY(ID_Tipo_Empleado) REFERENCES Tipo_Empleado(ID_Tipo_Empleado)
ON DELETE NO ACTION

)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Idioma(
ID_Idioma INT NOT NULL AUTO_INCREMENT,
Nombre_Idioma VARCHAR(40) NOT NULL,
PRIMARY KEY(ID_Idioma)
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Empleado_Idioma(
ID_Empleado_Idioma INT NOT NULL AUTO_INCREMENT,
Nivel_Idioma VARCHAR(20) NOT NULL,
FOREIGN KEY(ID_Idioma) REFERENCES Idioma(ID_Idioma),
FOREIGN KEY(ID_Empleado) REFERENCES Empleado(ID_Empleado)
ON DELETE NO ACTION
)ENGINE=InnoDB;






