
CREATE DATABASE IF NOT EXISTS PY2_E1;
USE PY2_E1;

-- ES PARA ELIMINAR LAS TABLAS DEL MODELO 
USE PY2_E1; 
SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS
Region,Ciudad,Codigo_Postal,Tipo,Persona,Compania,Categoria,Producto,Transaccion;
SET FOREIGN_KEY_CHECKS = 1;


CREATE TABLE IF NOT EXISTS Region(
ID_Region INT NOT NULL AUTO_INCREMENT,
Nombre_Region VARCHAR(40) NOT NULL,
PRIMARY KEY(ID_Region)
)ENGINE=InnoDB CHARACTER SET latin1;

CREATE TABLE IF NOT EXISTS Tipo(
ID_Tipo INT NOT NULL AUTO_INCREMENT,
Nombre_Tipo VARCHAR(5) NOT NULL,
PRIMARY KEY(ID_Tipo)
)ENGINE=InnoDB CHARACTER SET latin1;


CREATE TABLE IF NOT EXISTS Categoria(
ID_Categoria INT NOT NULL AUTO_INCREMENT,
Nombre_Categoria VARCHAR(40) NOT NULL,
PRIMARY KEY(ID_Categoria)
)ENGINE=InnoDB CHARACTER SET latin1;


CREATE TABLE IF NOT EXISTS Compania(
ID_Compania INT NOT NULL AUTO_INCREMENT,
Nombre_Compania VARCHAR(50) NOT NULL,
Contacto_Compania VARCHAR(40) NOT NULL,
Correo_Compania VARCHAR(50) NOT NULL,
Telefono_Compania VARCHAR(20) NOT NULL,
PRIMARY KEY(ID_Compania) 
)ENGINE=InnoDB CHARACTER SET latin1;


CREATE TABLE IF NOT EXISTS Ciudad(
ID_Ciudad INT NOT NULL AUTO_INCREMENT,
Nombre_Ciudad VARCHAR(40) NOT NULL,
PRIMARY KEY(ID_Ciudad),
Id_Region INT NOT NULL,
CONSTRAINT fk_Ciudad_Region
FOREIGN KEY(ID_Region) REFERENCES Region (ID_Region)
ON DELETE NO ACTION
)ENGINE=InnoDB CHARACTER SET latin1;


CREATE TABLE IF NOT EXISTS Codigo_Postal(
ID_Codigo_Postal INT NOT NULL AUTO_INCREMENT,
Numero_Codigo_Postal INT NOT NULL,
PRIMARY KEY(ID_Codigo_Postal),
ID_Ciudad INT NOT NULL,
CONSTRAINT fk_CPostal_Ciudad
FOREIGN KEY(ID_Ciudad) REFERENCES Ciudad(ID_Ciudad)
ON DELETE NO ACTION
)ENGINE=InnoDB CHARACTER SET latin1;


CREATE TABLE IF NOT EXISTS Persona(
ID_Persona INT NOT NULL AUTO_INCREMENT,
Nombre_Persona VARCHAR(40) NOT NULL,
Correo_Persona VARCHAR(50) NOT NULL,
Telefono_Persona VARCHAR(20) NOT NULL,
Fecha_Registro VARCHAR(20) NOT NULL,
Direccion VARCHAR(50) NOT NULL,
PRIMARY KEY(ID_Persona),
ID_Codigo_Postal INT NOT NULL,
ID_Tipo INT NOT NULL,
CONSTRAINT fk_Persona_CPostal
FOREIGN KEY(ID_Codigo_Postal) REFERENCES Codigo_Postal(ID_Codigo_Postal) ON DELETE NO ACTION,
CONSTRAINT fk_Persona_Tipo
FOREIGN KEY(ID_Tipo) REFERENCES Tipo(ID_Tipo) ON DELETE NO ACTION
)ENGINE=InnoDB CHARACTER SET latin1;


CREATE TABLE IF NOT EXISTS Producto(
ID_Producto INT NOT NULL AUTO_INCREMENT,
Nombre_Producto VARCHAR(40) NOT NULL,
Precio_Producto DECIMAL(19,2) NOT NULL,
PRIMARY KEY(ID_Producto),
ID_Categoria INT NOT NULL,
CONSTRAINT fk_Producto_Categoria
FOREIGN KEY(ID_Categoria) REFERENCES Categoria(ID_Categoria)
ON DELETE NO ACTION
)ENGINE=InnoDB CHARACTER SET latin1;


CREATE TABLE IF NOT EXISTS Transaccion(
ID_Transaccion INT NOT NULL AUTO_INCREMENT,
Cantidad INT NOT NULL,
Total_Transaccion DECIMAL(19,2) NOT NULL,
PRIMARY KEY(ID_Transaccion),
ID_Compania INT NOT NULL,
ID_Persona INT NOT NULL,
ID_Producto INT NOT NULL,
CONSTRAINT fk_Transaccion_Compania
FOREIGN KEY(ID_Compania) REFERENCES Compania(ID_Compania)
ON DELETE NO ACTION,
CONSTRAINT fk_Transaccion_Persona
FOREIGN KEY(ID_Persona) REFERENCES Persona(ID_Persona)
ON DELETE NO ACTION,
CONSTRAINT fk_Transaccion_Producto
FOREIGN KEY(ID_Producto) REFERENCES Producto(ID_Producto)
ON DELETE NO ACTION
)ENGINE=InnoDB CHARACTER SET latin1;



