
CREATE DATABASE IF NOT EXISTS PY2_E2;

USE PY2_E2;

DROP TABLE IF EXISTS Temporal1;

USE PY2_E2;
Create temporary table  Temporal1(
INVENTO varchar(50),
INVENTOR varchar(50),
PROFESIONAL_ASIGANDO_AL_INVENTO varchar(50),
EL_PROFESIONAL_ES_JEFE_DEL_AREA varchar(50),
FECHA_CONTRATO_PROFESIONAL varchar(20),
SALARIO int,
COMISION int,
AREA_INVEST_DEL_PROF varchar(50),
RANKING int,
ANIO_DEL_INVENTO int, 
PAIS_DEL_INVENTO varchar(50),
PAIS_DEL_INVENTOR varchar(50),
REGION_DEL_PAIS varchar(50),
CAPITAL varchar(50),
POBLACION_DEL_PAIS int,
AREA_EN_KM2 int,
FRONTERA_CON varchar(50),
NORTE varchar(5),
SUR varchar(5),
ESTE varchar(5),
OESTE varchar(5)
);
LOAD DATA LOCAL INFILE "/home/mario/Escritorio/Bases1/uno.csv"
INTO TABLE Temporal1
CHARACTER SET 'utf8'
FIELDS TERMINATED BY  ','
optionally enclosed by '\''
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(INVENTO,INVENTOR,PROFESIONAL_ASIGANDO_AL_INVENTO,EL_PROFESIONAL_ES_JEFE_DEL_AREA,@var_fecha,SALARIO,COMISION,AREA_INVEST_DEL_PROF
,RANKING,ANIO_DEL_INVENTO,PAIS_DEL_INVENTO,PAIS_DEL_INVENTOR,REGION_DEL_PAIS,CAPITAL,POBLACION_DEL_PAIS,AREA_EN_KM2,FRONTERA_CON
,NORTE,SUR,ESTE,OESTE)
SET FECHA_CONTRATO_PROFESIONAL= STR_TO_DATE(@var_fecha,'%d/%m/%Y');

select * from Temporal1;
select count(*) from Temporal1;

-- *************************************************** TEMPORAL2 ******************************************************************

Create temporary table  Temporal2(
NOMBRE_ENCUESTA varchar(50),
PREGUNTA varchar(300),
RESPUESTAS_POSIBLES varchar(5),
RESPUESTA_CORRECTA varchar(5),
PAIS varchar(50),
RESPUESTA_PAIS varchar(5)
);
LOAD DATA LOCAL INFILE "/home/mario/Escritorio/Bases1/dos.csv"
INTO TABLE Temporal2
CHARACTER SET 'utf8'
FIELDS TERMINATED BY  ','
optionally enclosed by '\''
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(INVENTO,INVENTOR,PROFESIONAL_ASIGANDO_AL_INVENTO,EL_PROFESIONAL_ES_JEFE_DEL_AREA,@var_fecha,SALARIO,COMISION,AREA_INVEST_DEL_PROF
,RANKING,ANIO_DEL_INVENTO,PAIS_DEL_INVENTO,PAIS_DEL_INVENTOR,REGION_DEL_PAIS,CAPITAL,POBLACION_DEL_PAIS,AREA_EN_KM2,FRONTERA_CON
,NORTE,SUR,ESTE,OESTE)
SET FECHA_CONTRATO_PROFESIONAL= STR_TO_DATE(@var_fecha,'%d/%m/%Y');









