CREATE DATABASE Enunciado5;
USE Enunciado5;

CREATE TABLE IF NOT EXISTS Bodega(
ID_Tipo_Bodega INT NOT NULL AUTO_INCREMENT,
Nombre_Tipo_Bodega VARCHAR(40) NOT NULL,
Direccion VARCHAR(40) NOT NULL,
Cantidad_Parte_Producto INT NOT NULL,
PRIMARY KEY(ID_Tipo_Bodega)
)ENGINE=InnoDB;'sólo existe soporte para claves foráneas en tablas de tipo InnoDB.'


CREATE TABLE IF NOT EXISTS Pais(
ID_Pais INT NOT NULL AUTO_INCREMENT,
Nombre_Pais VARCHAR(40) NOT NULL,
PRIMARY KEY(ID_Pais)
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Ciudad(
ID_Ciudad INT NOT NULL AUTO_INCREMENT,
Codigo_Ciudad INT NOT NULL,
Nombre_Ciudad VARCHAR(40) NOT NULL,
PRIMARY KEY(ID_Ciudad),
FOREIGN KEY(ID_Pais) REFERENCES Pais(ID_Pais)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Cliente(
ID_Cliente INT NOT NULL AUTO_INCREMENT,
Nombre_Cliente VARCHAR(40) NOT NULL,
Direccion VARCHAR(40) NOT NULL,
PRIMARY KEY(ID_Cliente),
FOREIGN KEY(ID_Pais) REFERENCES Pais(ID_Pais)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Proveedor(
ID_Proveedor INT NOT NULL AUTO_INCREMENT,
Nombre_Proveedor VARCHAR(40) NOT NULL,
Telefono INT NOT NULL,
Compañia VARCHAR(40) NOT NULL,
Direccion VARCHAR(40) NOT NULL,
PRIMARY KEY(ID_Proveedor),
FOREIGN KEY(ID_Pais) REFERENCES Pais(ID_Pais),
FOREIGN KEY(ID_Parte) REFERENCES Parte(ID_Parte)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Detalle_Factura(
ID_Detalle INT NOT NULL AUTO_INCREMENT,
Fecha_Extencion DATE NOT NULL,
Descripcion_Reclamo VARCHAR(40),'opcional'
Monto_Total INT NOT NULL,
PRIMARY KEY(ID_Detalle ),
FOREIGN KEY(ID_Proveedor) REFERENCES Proveedor(ID_Proveedor)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Soporte_Tecnico(
ID_Soporte INT NOT NULL AUTO_INCREMENT,
Hora_Soporte TIME NOT NULL,
Fecha_Soporte DATE NOT NULL,
Monto_Reembolso INT,'es opcional'
PRIMARY KEY(ID_Soporte),
FOREIGN KEY(ID_Cliente) REFERENCES Cliente(ID_Cliente)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Detalle_Pedido(
ID_Detalle INT NOT NULL AUTO_INCREMENT,
Fecha_Realizo_Pedido DATE NOT NULL,
Total_Pedido INT NOT NULL,
PRIMARY KEY(ID_Detalle),
FOREIGN KEY(ID_Cliente) REFERENCES Cliente(ID_Cliente)
ON DELETE NO ACTION
)ENGINE=InnoDB;



CREATE TABLE IF NOT EXISTS Producto(
ID_Producto INT NOT NULL AUTO_INCREMENT,
Nombre_Producto VARCHAR(40) NOT NULL,
Marca_Producto VARCHAR(40) NOT NULL,
HoraFecha_Finalizo_Producto DATETIME NOT NULL,
Tipo_Producto VARCHAR(40) NOT NULL,
PRIMARY KEY(ID_Producto),
FOREIGN KEY(ID_Tipo_Bodega) REFERENCES Bodega(ID_Tipo_Bodega),
FOREIGN KEY(ID_Detalle) REFERENCES Detalle_Pedido(ID_Detalle)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Etapa(
ID_Etapa INT NOT NULL AUTO_INCREMENT,
Nombre_Etapa VARCHAR(40) NOT NULL,
Estado_Etapa VARCHAR(40) NOT NULL,
Costo_Etapa INT NOT NULL,
Gasto_Etapa INT NOT NULL,
PRIMARY KEY(ID_Etapa),
FOREIGN KEY(ID_Producto) REFERENCES Producto(ID_Producto)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Parte(
ID_Parte INT NOT NULL AUTO_INCREMENT,
Nombre_Parte VARCHAR(40) NOT NULL,
Color_Parte VARCHAR(40) NOT NULL,
Tipo_Parte VARCHAR(20) NOT NULL,
Garantia VARCHAR(20) NOT NULL,
Costo_Parte INT NOT NULL,
PRIMARY KEY(ID_Parte),
FOREIGN KEY(ID_Parte) REFERENCES Parte(ID_Parte),
FOREIGN KEY(ID_Etapa) REFERENCES Etapa(ID_Etapa)
ON DELETE NO ACTION
)ENGINE=InnoDB;


CREATE TABLE IF NOT EXISTS Linea_Ensamblaje(
ID_Linea_Ensamblaje INT NOT NULL AUTO_INCREMENT,
Nombre_Linea_Ensamblaje VARCHAR(40) NOT NULL,
Tipo VARCHAR(40) NOT NULL,
Descripcion VARCHAR(40) NOT NULL,
PRIMARY KEY(ID_Linea_Ensamblaje),
FOREIGN KEY(ID_Producto) REFERENCES Producto(ID_Producto),
FOREIGN KEY(ID_Empleado) REFERENCES Empleado(ID_Empleado)
ON DELETE NO ACTION
)ENGINE=InnoDB;



CREATE TABLE IF NOT EXISTS Empleado(
ID_Empleado INT NOT NULL AUTO_INCREMENT,
Nombre_Empleado VARCHAR(40) NOT NULL,
Direccion VARCHAR(40) NOT NULL,
Telefono INT NOT NULL,
Correo VARCHAR(40) NOT NULL,
PRIMARY KEY(ID_Empleado),
FOREIGN KEY(ID_Linea_Ensamblaje) REFERENCES Linea_Ensamblaje(ID_Linea_Ensamblaje)
ON DELETE NO ACTION
)ENGINE=InnoDB;



CREATE TABLE IF NOT EXISTS Tipo_Empleado(
ID_Tipo_Empleado INT NOT NULL AUTO_INCREMENT,
Nombre_Empleado VARCHAR(40) NOT NULL,
Sueldo INT NOT NULL,
Jornada_Laboral VARCHAR(40),'opcional'
Horas_Laborales TIME,'opocional'
Hora_Entrada_Laboral TIME NOT NULL,
Hora_Salida_Laboral TIME NOT NULL,
PRIMARY KEY(ID_Tipo_Empleado),
FOREIGN KEY(ID_Empleado) REFERENCES Empleado(ID_Empleado)
ON DELETE NO ACTION
)ENGINE=InnoDB;




